name: Lint

on:
  - push
  - pull_request

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          
      - name: Setup node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r dev_requirements.txt
          
      - name: Install prettier
        run: |
          npm install -g prettier@2.4.1
          
      - name: TS Format (yarn prettier --write **/*.ts to format files locally)
        working-directory: ./output-webview/
        run: prettier --check **/*.ts
        
      - name: Black check
        run: |
          black --check src tests --exclude=vendored --exclude=libs
          
      - name: mypy create env
        run: |
          python -m venv .venv
          source ./.venv/bin/activate
          
          python -m pip install -r tests/test_requirements.txt
          python -m pip install -r dev_requirements.txt
          python -m pip install robotframework
          
          echo $PWD/src >> .venv/lib/python3.8/site-packages/rf_src.pth
          echo $PWD/tests >> .venv/lib/python3.8/site-packages/rf_src.pth
          

      - name: mypy robocorp-logging
        run: |
          source ./.venv/bin/activate
          mypy --follow-imports=silent --show-column-numbers $PWD/src $PWD/tests
          
          